USE GD2C2023
GO

-------------------------------------------------------------------------------------------------
-----------------------------------DROP DE TABLES------------------------------------------------
-------------------------------------------------------------------------------------------------

IF OBJECT_ID('SYSTEAM.VENTA', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.VENTA
GO

IF OBJECT_ID('SYSTEAM.PAGO_VENTA', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.PAGO_VENTA
GO

IF OBJECT_ID('SYSTEAM.MONEDA', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.MONEDA
GO

IF OBJECT_ID('SYSTEAM.ANUNCIO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.ANUNCIO
GO

IF OBJECT_ID('SYSTEAM.TIPO_ANUNCIO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.TIPO_ANUNCIO
GO

IF OBJECT_ID('SYSTEAM.AGENTE', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.AGENTE
GO

IF OBJECT_ID ('SYSTEAM.SUCURSAL','U') IS NOT NULL
	DROP TABLE SYSTEAM.SUCURSAL
GO 

IF OBJECT_ID ('SYSTEAM.LOCALIDAD', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.LOCALIDAD
GO

IF OBJECT_ID('SYSTEAM.PROVINCIA', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.PROVINCIA
GO

IF OBJECT_ID ('SYSTEAM.INMUEBLE', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.INMUEBLE
GO

IF OBJECT_ID ('SYSTEAM.INMUEBLE_ESTADO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.INMUEBLE_ESTADO
GO

IF OBJECT_ID('SYSTEAM.DETALLE_INMUEBLE', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.DETALLE_INMUEBLE
GO

IF OBJECT_ID('SYSTEAM.PROPIETARIO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.PROPIETARIO
GO

IF OBJECT_ID ('SYSTEAM.COMPRADOR', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.COMPRADOR
GO

IF OBJECT_ID ('SYSTEAM.MEDIO_PAGO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.MEDIO_PAGO
GO

IF OBJECT_ID ('SYSTEAM.ALQUILER', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.ALQUILER
GO

IF OBJECT_ID ('SYSTEAM.PAGO_ALQUILER', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.PAGO_ALQUILER 
GO

IF OBJECT_ID ('SYSTEAM.DETALLE_ALQUILER', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.DETALLE_ALQUILER
GO

IF OBJECT_ID ('SYSTEAM.INQUILINO', 'U') IS NOT NULL
	DROP TABLE SYSTEAM.INQUILINO
GO

-------------------------------------------------------------------------------------------------
-----------------------------------DROP DE PROCEDURES--------------------------------------------
-------------------------------------------------------------------------------------------------

IF OBJECT_ID('SYSTEAM.CARGAR_VENTA') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_VENTA
GO

IF OBJECT_ID('SYSTEAM.CARGAR_PAGO_VENTA') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_PAGO_VENTA
GO

IF OBJECT_ID('SYSTEAM.CARGAR_MONEDA') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_MONEDA
GO

IF OBJECT_ID('SYSTEAM.CARGAR_ANUNCIO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_ANUNCIO
GO

IF OBJECT_ID('SYSTEAM.CARGAR_TIPO_ANUNCIO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_TIPO_ANUNCIO
GO

IF OBJECT_ID('SYSTEAM.CARGAR_AGENTE') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_AGENTE
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_SUCURSAL') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_SUCURSAL
GO 

IF OBJECT_ID ('SYSTEAM.CARGAR_LOCALIDAD') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_LOCALIDAD
GO

IF OBJECT_ID('SYSTEAM.CARGAR_PROVINCIA') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_PROVINCIA
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_INMUEBLE') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_INMUEBLE
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_INMUEBLE_ESTADO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_INMUEBLE_ESTADO
GO

IF OBJECT_ID('SYSTEAM.CARGAR_DETALLE_INMUEBLE') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_DETALLE_INMUEBLE
GO

IF OBJECT_ID('SYSTEAM.CARGAR_PROPIETARIO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_PROPIETARIO
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_COMPRADOR') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_COMPRADOR
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_MEDIO_PAGO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_MEDIO_PAGO
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_ALQUILER') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_ALQUILER
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_PAGO_ALQUILER') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_PAGO_ALQUILER 
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_DETALLE_ALQUILER') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_DETALLE_ALQUILER
GO

IF OBJECT_ID ('SYSTEAM.CARGAR_INQUILINO') IS NOT NULL
	DROP PROCEDURE SYSTEAM.CARGAR_INQUILINO
GO

-------------------------------------------------------------------------------------------------
--------------------------------------------SCHEMA-----------------------------------------------
-------------------------------------------------------------------------------------------------

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'SYSTEAM')
	DROP SCHEMA SYSTEAM
GO

CREATE SCHEMA SYSTEAM
GO

-------------------------------------------------------------------------------------------------
----------------------------------------CREATE TABLES--------------------------------------------
-------------------------------------------------------------------------------------------------

CREATE TABLE SYSTEAM.VENTA (
	VENTA_CODIGO numeric(18,0) PRIMARY KEY,
	VENTA_FECHA datetime,
	VENTA_PRECIO_VENTA numeric(18,2),
	VENTA_COMISION numeric(18,2),
	MONEDA_CODIGO numeric(18,0),
	COMPRADOR_CODIGO numeric(18,0),
	ANUNCIO_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.PAGO_VENTA (
	PAGO_VENTA_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	PAGO_VENTA_IMPORTE numeric(18,2),
	MONEDA_CODIGO numeric(18,0),
	PAGO_VENTA_COTIZACION numeric(18,2),
	MEDIO_PAGO_CODIGO numeric(18,0),
	VENTA_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.MONEDA(
	MONEDA_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	MONEDA_NOMBRE nvarchar(100)
);

CREATE TABLE SYSTEAM.ANUNCIO(
	ANUNCIO_CODIGO numeric(18,0) PRIMARY KEY,
	ANUNCIO_FECHA_PUBLICACION datetime,
	ANUNCIO_PRECIO_PUBLICADO numeric(18,0),
	TIPO_ANUNCIO_CODIGO numeric(18,0),
	ANUNCIO_COSTO_ANUNCIO numeric(18,0),
	ANUNCIO_FECHA_FINALIZACION datetime,
	MONEDA_CODIGO numeric(18,0),
	ANUNCIO_ESTADO nvarchar(10),
	ANUNCIO_TIPO_PERIODO nvarchar(100),
	AGENTE_CODIGO numeric(18,0),
	INMUEBLE_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.TIPO_ANUNCIO(
	TIPO_ANUNCIO_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	TIPO_ANUNCIO_NOMBRE nvarchar(100)
);

CREATE TABLE SYSTEAM.AGENTE(
	AGENTE_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	AGENTE_NOMBRE nvarchar(100),
	AGENTE_APELLIDO nvarchar(100),
	AGENTE_DNI numeric(18,0),
	AGENTE_FECHA_REGISTRO datetime,
	AGENTE_TELEFONO numeric(18,0),
	AGENTE_MAIL nvarchar(100),
	AGENTE_FECHA_NAC datetime,
	SUCURSAL_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.SUCURSAL(
	SUCURSAL_CODIGO numeric(18,0) PRIMARY KEY,
	SUCURSAL_NOMBRE nvarchar(100),
	SUCURSAL_DIRECCION nvarchar(100),
	SUCURSAL_TELEFONO nvarchar(100),
	LOCALIDAD_CODIGO numeric(18,0),
	PROVINCIA_CODIGO numeric(18,0)
);


CREATE TABLE SYSTEAM.LOCALIDAD(
	LOCALIDAD_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	LOCALIDAD_NOMBRE nvarchar(100)
);

CREATE TABLE SYSTEAM.PROVINCIA(
	PROVINCIA_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	PROVINCIA_NOMBRE nvarchar(100)
);

CREATE TABLE SYSTEAM.INMUEBLE(
	INMUEBLE_CODIGO numeric(18,0) PRIMARY KEY,
	PROPIETARIO_CODIGO numeric(18,0),
	INMUEBLE_NOMBRE nvarchar(100),
	INMUEBLE_DESCRIPCION nvarchar(100),
	INMUEBLE_DIRECCION nvarchar(100),
	INMUEBLE_EXPENSAS numeric(18,2),
	INMUEBLE_BARRIO nvarchar(100),
	LOCALIDAD_CODIGO numeric(18,0),
	PROVINCIA_CODIGO numeric(18,0),
	INMUEBLE_ESTADO_CODIGO numeric(18,0),
	DETALLE_INMUEBLE_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.INMUEBLE_ESTADO(
	INMUEBLE_ESTADO_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	INMUEBLE_ESTADO nvarchar(100)
);

CREATE TABLE SYSTEAM.DETALLE_INMUEBLE(
	DETALLE_INMUEBLE_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	INMUEBLE_TIPO_INMUEBLE nvarchar(50),
	INMUEBLE_CARACTERISTICA_WIFI numeric(18,0),
	INMUEBLE_CARACTERISTICA_CABLE numeric(18,0),
	INMUEBLE_CARACTERISTICA_CALEFACCION numeric(18,0),
	INMUEBLE_CARACTERISTICA_GAS numeric(18,0),
	INMUEBLE_CANT_AMBIENTES nvarchar(100),
	INMUEBLE_ORIENTACION nvarchar(100),
	INMUEBLE_DISPOSICION nvarchar(100),
	INMUEBLE_SUPERFICIETOTAL numeric(18,2),
	INMUEBLE_ANTIGUEDAD numeric(18,0)
);

CREATE TABLE SYSTEAM.PROPIETARIO(
	PROPIETARIO_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	PROPIETARIO_NOMBRE nvarchar(100),
	PROPIETARIO_APELLIDO nvarchar(100),
	PROPIETARIO_DNI numeric(18,0),
	PROPIETARIO_FECHA_REGISTRO datetime,
	PROPIETARIO_TELEFONO numeric(18,0),
	PROPIETARIO_MAIL nvarchar(255),
	PROPIETARIO_FECHA_NAC datetime,
);

CREATE TABLE SYSTEAM.COMPRADOR(
	COMPRADOR_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	COMPRADOR_NOMBRE nvarchar(100),
	COMPRADOR_APELLIDO nvarchar(100),
	COMPRADOR_DNI numeric(18,0),
	COMPRADOR_FECHA_REGISTRO datetime,
	COMPRADOR_TELEFONO numeric(18,0),
	COMPRADOR_MAIL nvarchar(100),
	COMPRADOR_FECHA_NAC datetime
);

CREATE TABLE SYSTEAM.MEDIO_PAGO(
    MEDIO_PAGO_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	MEDIO_PAGO_NOMBRE nvarchar(100)
);


CREATE TABLE SYSTEAM.ALQUILER(
	ALQUILER_CODIGO numeric(18,0) PRIMARY KEY,
	ALQUILER_FECHA_INICIO datetime,
	ALQUILER_FECHA_FIN datetime,
	ALQUILER_CANT_PERIODOS numeric(18,0),
	ALQUILER_DEPOSITO numeric(18,2),
	ALQUILER_COMISION numeric(18,2),
	ALQUILER_GASTOS_AVERIGUA numeric(18,2),
	ALQUILER_ESTADO nvarchar(100),
	INQUILINO_CODIGO numeric(18,0),
	ANUNCIO_CODIGO numeric(18,0)
);


CREATE TABLE SYSTEAM.PAGO_ALQUILER(
	PAGO_ALQUILER_CODIGO numeric(18,0) PRIMARY KEY,
	PAGO_ALQUILER_FECHA datetime,
	PAGO_ALQUILER_FECHA_VENCIMIENTO datetime,
	PAGO_ALQUILER_NRO_PERIODO numeric(18,0),
	PAGO_ALQUILER_DESC nvarchar(100),
	PAGO_ALQUILER_FECHA_INI datetime,
	PAGO_ALQUILER_FECHA_FIN datetime,
	PAGO_ALQUILER_IMPORTE numeric(18,2),
	MEDIO_PAGO_CODIGO numeric(18,0),
	ALQUILER_CODIGO numeric(18,0)
);

CREATE TABLE SYSTEAM.DETALLE_ALQUILER(
	DETALLE_ALQ_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	ALQUILER_CODIGO numeric(18,0),
	DETALLE_ALQ_NRO_PERIODO_INI numeric(18,0),
	DETALLE_ALQ_NRO_PERIODO_FIN numeric(18,0),
	DETALLE_ALQUILER_PRECIO numeric(18,2)
);


CREATE TABLE SYSTEAM.INQUILINO(
	INQUILINO_CODIGO numeric(18,0) IDENTITY(1,1) PRIMARY KEY,
	INQUILINO_NOMBRE nvarchar(100),
	INQUILINO_APELLIDO nvarchar(100),
	INQUILINO_DNI numeric(18,0),
	INQUILINO_FECHA_REGISTRO datetime,
	INQUILINO_TELEFONO numeric(18,0),
	INQUILINO_MAIL nvarchar(100),
	INQUILINO_FECHA_NAC datetime
);

-------------------
--- ALTERS ----
-------------------
-- VENTAS
ALTER TABLE SYSTEAM.VENTA ADD CONSTRAINT FK_VEN_MON_MONEDA_CODIGO FOREIGN KEY (MONEDA_CODIGO) REFERENCES SYSTEAM.MONEDA(MONEDA_CODIGO);
ALTER TABLE SYSTEAM.VENTA ADD CONSTRAINT FK_VEN_COM_COMPRADOR_CODIGO FOREIGN KEY (COMPRADOR_CODIGO) REFERENCES SYSTEAM.COMPRADOR(COMPRADOR_CODIGO);
ALTER TABLE SYSTEAM.VENTA ADD CONSTRAINT FK_VEN_ANU_ANUNCIO_CODIGO FOREIGN KEY (ANUNCIO_CODIGO) REFERENCES SYSTEAM.ANUNCIO(ANUNCIO_CODIGO);

-- PAGO_VENTA
ALTER TABLE SYSTEAM.PAGO_VENTA ADD CONSTRAINT FK_PAG_MON_MONEDA_CODIGO FOREIGN KEY (MONEDA_CODIGO) REFERENCES SYSTEAM.MONEDA(MONEDA_CODIGO);
ALTER TABLE SYSTEAM.PAGO_VENTA ADD CONSTRAINT FK_PAG_MED_MEDIO_PAGO_CODIGO FOREIGN KEY (MEDIO_PAGO_CODIGO) REFERENCES SYSTEAM.MEDIO_PAGO(MEDIO_PAGO_CODIGO);
ALTER TABLE SYSTEAM.PAGO_VENTA ADD CONSTRAINT FK_PAG_VEN_VENTA_CODIGO FOREIGN KEY (VENTA_CODIGO) REFERENCES SYSTEAM.VENTA(VENTA_CODIGO);

-- ANUNCIO
ALTER TABLE SYSTEAM.ANUNCIO ADD CONSTRAINT FK_ANU_TIP_TIPO_ANUNCIO_CODIGO FOREIGN KEY (TIPO_ANUNCIO_CODIGO) REFERENCES SYSTEAM.TIPO_ANUNCIO(TIPO_ANUNCIO_CODIGO);
ALTER TABLE SYSTEAM.ANUNCIO ADD CONSTRAINT FK_ANU_AGE_AGENTE_CODIGO FOREIGN KEY (AGENTE_CODIGO) REFERENCES SYSTEAM.AGENTE(AGENTE_CODIGO);
ALTER TABLE SYSTEAM.ANUNCIO ADD CONSTRAINT FK_ANU_INM_INMUEBLE_CODIGO FOREIGN KEY (INMUEBLE_CODIGO) REFERENCES SYSTEAM.INMUEBLE(INMUEBLE_CODIGO);

-- AGENTE
ALTER TABLE SYSTEAM.AGENTE ADD CONSTRAINT FK_AGE_SUC_SUCURSAL_CODIGO FOREIGN KEY (SUCURSAL_CODIGO) REFERENCES SYSTEAM.SUCURSAL(SUCURSAL_CODIGO);

-- SUCURSAL
ALTER TABLE SYSTEAM.SUCURSAL ADD CONSTRAINT FK_SUC_LOC_LOCALIDAD_CODIGO FOREIGN KEY (LOCALIDAD_CODIGO) REFERENCES SYSTEAM.LOCALIDAD(LOCALIDAD_CODIGO);
ALTER TABLE SYSTEAM.SUCURSAL ADD CONSTRAINT FK_SUC_PRO_PROVINCIA_CODIGO FOREIGN KEY (PROVINCIA_CODIGO) REFERENCES SYSTEAM.PROVINCIA(PROVINCIA_CODIGO);

-- INMUEBLE
ALTER TABLE SYSTEAM.INMUEBLE ADD CONSTRAINT FK_INM_LOC_LOCALIDAD_CODIGO FOREIGN KEY (LOCALIDAD_CODIGO) REFERENCES SYSTEAM.LOCALIDAD(LOCALIDAD_CODIGO);
ALTER TABLE SYSTEAM.INMUEBLE ADD CONSTRAINT FK_INM_PRO_PROVINCIA_CODIGO FOREIGN KEY (PROVINCIA_CODIGO) REFERENCES SYSTEAM.PROVINCIA(PROVINCIA_CODIGO);
ALTER TABLE SYSTEAM.INMUEBLE ADD CONSTRAINT FK_INM_EST_INMUEBLE_ESTADO_CODIGO FOREIGN KEY (INMUEBLE_ESTADO_CODIGO) REFERENCES SYSTEAM.INMUEBLE_ESTADO(INMUEBLE_ESTADO_CODIGO);
ALTER TABLE SYSTEAM.INMUEBLE ADD CONSTRAINT FK_INM_DET_DETALLE_INMUEBLE_CODIGO FOREIGN KEY (DETALLE_INMUEBLE_CODIGO) REFERENCES SYSTEAM.DETALLE_INMUEBLE(DETALLE_INMUEBLE_CODIGO);

-- ALQUILER
ALTER TABLE SYSTEAM.ALQUILER ADD CONSTRAINT FK_ALQ_INQ_INQUILINO_CODIGO FOREIGN KEY (INQUILINO_CODIGO) REFERENCES SYSTEAM.INQUILINO(INQUILINO_CODIGO);
ALTER TABLE SYSTEAM.ALQUILER ADD CONSTRAINT FK_ALQ_ANU_ANUNCIO_CODIGO FOREIGN KEY (ANUNCIO_CODIGO) REFERENCES SYSTEAM.ANUNCIO(ANUNCIO_CODIGO);

-- DETALLE_ALQUILER
ALTER TABLE SYSTEAM.DETALLE_ALQUILER ADD CONSTRAINT FK_DET_ALQ_ALQUILER_CODIGO FOREIGN KEY (ALQUILER_CODIGO) REFERENCES SYSTEAM.ALQUILER(ALQUILER_CODIGO);

-- PAGO_ALQUILER
ALTER TABLE SYSTEAM.PAGO_ALQUILER ADD CONSTRAINT FK_PAGALQ_MED_MEDIO_PAGO_CODIGO FOREIGN KEY (MEDIO_PAGO_CODIGO) REFERENCES SYSTEAM.MEDIO_PAGO(MEDIO_PAGO_CODIGO);
ALTER TABLE SYSTEAM.PAGO_ALQUILER ADD CONSTRAINT FK_PAGALQ_ALQ_ALQUILER_CODIGO FOREIGN KEY (ALQUILER_CODIGO) REFERENCES SYSTEAM.ALQUILER(ALQUILER_CODIGO);

-------------------
--- PROCEDURES ----
-------------------

CREATE PROCEDURE SYSTEAM.CARGAR_MONEDA
AS
BEGIN
	INSERT INTO SYSTEAM.MONEDA
		(MONEDA_NOMBRE) VALUES ('Moneda Pesos');
	INSERT INTO SYSTEAM.MONEDA
		(MONEDA_NOMBRE) VALUES ('Moneda Dolares');
END 
GO

CREATE PROCEDURE SYSTEAM.CARGAR_TIPO_ANUNCIO
AS
BEGIN
	INSERT INTO SYSTEAM.TIPO_ANUNCIO
		(TIPO_ANUNCIO_NOMBRE) VALUES ('Tipo Operación Alquiler Contrato');
	INSERT INTO SYSTEAM.TIPO_ANUNCIO
		(TIPO_ANUNCIO_NOMBRE) VALUES ('Tipo Operación Alquiler Temporario');
	INSERT INTO SYSTEAM.TIPO_ANUNCIO
		(TIPO_ANUNCIO_NOMBRE) VALUES ('Tipo Operación Venta');
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_LOCALIDAD
AS
BEGIN
	WITH Localidades AS (
		SELECT SUCURSAL_LOCALIDAD AS LOCALIDAD_NOMBRE FROM GD_ESQUEMA.MAESTRA
		UNION
		SELECT INMUEBLE_LOCALIDAD AS LOCALIDAD_NOMBRE FROM GD_ESQUEMA.MAESTRA
	)
	INSERT INTO SYSTEAM.LOCALIDAD (LOCALIDAD_NOMBRE)
	SELECT DISTINCT LOCALIDAD_NOMBRE
	FROM Localidades
	WHERE LOCALIDAD_NOMBRE IS NOT NULL
END;
GO

CREATE PROCEDURE SYSTEAM.CARGAR_PROVINCIA
AS
BEGIN
	WITH Provincias AS (
		SELECT SUCURSAL_PROVINCIA AS PROVINCIA_NOMBRE FROM GD_ESQUEMA.MAESTRA
		UNION
		SELECT INMUEBLE_PROVINCIA AS PROVINCIA_NOMBRE FROM GD_ESQUEMA.MAESTRA
	)
	INSERT INTO SYSTEAM.PROVINCIA (PROVINCIA_NOMBRE)
	SELECT DISTINCT PROVINCIA_NOMBRE
	FROM Provincias
	WHERE PROVINCIA_NOMBRE IS NOT NULL
END 
GO

CREATE PROCEDURE SYSTEAM.CARGAR_SUCURSAL
AS
BEGIN
	INSERT INTO SYSTEAM.SUCURSAL
		(SUCURSAL_CODIGO, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_TELEFONO, LOCALIDAD_CODIGO, PROVINCIA_CODIGO)
		SELECT DISTINCT m.SUCURSAL_CODIGO, m.SUCURSAL_NOMBRE, m.SUCURSAL_DIRECCION, m.SUCURSAL_TELEFONO, l.LOCALIDAD_CODIGO, p.PROVINCIA_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN LOCALIDAD l on l.LOCALIDAD_NOMBRE = m.SUCURSAL_LOCALIDAD
		JOIN PROVINCIA p on p.PROVINCIA_NOMBRE = m.SUCURSAL_PROVINCIA
		WHERE m.SUCURSAL_CODIGO is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_AGENTE
AS
BEGIN
	INSERT INTO SYSTEAM.AGENTE
		(AGENTE_NOMBRE, AGENTE_APELLIDO, AGENTE_DNI, AGENTE_FECHA_REGISTRO, AGENTE_TELEFONO, AGENTE_MAIL, AGENTE_FECHA_NAC, SUCURSAL_CODIGO)
		SELECT DISTINCT m.AGENTE_NOMBRE, m.AGENTE_APELLIDO, m.AGENTE_DNI, m.AGENTE_FECHA_REGISTRO, m.AGENTE_TELEFONO, m.AGENTE_MAIL, m.AGENTE_FECHA_NAC, s.SUCURSAL_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN SUCURSAL s on s.SUCURSAL_CODIGO = m.SUCURSAL_CODIGO
		WHERE m.AGENTE_DNI is not null
END 
GO

CREATE PROCEDURE SYSTEAM.CARGAR_PROPIETARIO
AS 
BEGIN
	INSERT INTO SYSTEAM.PROPIETARIO
		(PROPIETARIO_NOMBRE, PROPIETARIO_APELLIDO, PROPIETARIO_DNI, PROPIETARIO_FECHA_REGISTRO, PROPIETARIO_TELEFONO, PROPIETARIO_MAIL, PROPIETARIO_FECHA_NAC)
		SELECT DISTINCT m.PROPIETARIO_NOMBRE, m.PROPIETARIO_APELLIDO, m.PROPIETARIO_DNI, m.PROPIETARIO_FECHA_REGISTRO, m.PROPIETARIO_TELEFONO, m.PROPIETARIO_MAIL, m.PROPIETARIO_FECHA_NAC
		FROM GD_ESQUEMA.MAESTRA m
		WHERE m.PROPIETARIO_DNI is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_COMPRADOR
AS
BEGIN
	INSERT INTO SYSTEAM.COMPRADOR
		(COMPRADOR_NOMBRE, COMPRADOR_APELLIDO, COMPRADOR_DNI, COMPRADOR_FECHA_REGISTRO, COMPRADOR_TELEFONO, COMPRADOR_MAIL, COMPRADOR_FECHA_NAC)
		SELECT DISTINCT m.COMPRADOR_NOMBRE, m.COMPRADOR_APELLIDO, m.COMPRADOR_DNI, m.COMPRADOR_FECHA_REGISTRO, m.COMPRADOR_TELEFONO, m.COMPRADOR_MAIL, m.COMPRADOR_FECHA_NAC
		FROM GD_ESQUEMA.MAESTRA m
		WHERE m.COMPRADOR_DNI is not null
END
GO	

CREATE PROCEDURE SYSTEAM.CARGAR_INQUILINO
AS
BEGIN
	INSERT INTO SYSTEAM.INQUILINO
		(INQUILINO_NOMBRE, INQUILINO_APELLIDO, INQUILINO_DNI, INQUILINO_FECHA_REGISTRO, INQUILINO_TELEFONO, INQUILINO_MAIL, INQUILINO_FECHA_NAC)
		SELECT DISTINCT m.INQUILINO_NOMBRE, m.INQUILINO_APELLIDO, m.INQUILINO_DNI, m.INQUILINO_FECHA_REGISTRO, m.INQUILINO_TELEFONO, m.INQUILINO_MAIL, m.INQUILINO_FECHA_NAC
		FROM GD_ESQUEMA.MAESTRA m
		WHERE m.INQUILINO_DNI is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_INMUEBLE_ESTADO
AS
BEGIN
	INSERT INTO SYSTEAM.INMUEBLE_ESTADO
		(INMUEBLE_ESTADO)
		SELECT DISTINCT INMUEBLE_ESTADO AS INMUEBLE_ESTADO 
		FROM GD_ESQUEMA.MAESTRA m
		WHERE m.INMUEBLE_ESTADO is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_DETALLE_INMUEBLE
AS 
BEGIN
	INSERT INTO SYSTEAM.DETALLE_INMUEBLE
		(INMUEBLE_TIPO_INMUEBLE, INMUEBLE_CARACTERISTICA_WIFI, INMUEBLE_CARACTERISTICA_CABLE, INMUEBLE_CARACTERISTICA_CALEFACCION, INMUEBLE_CARACTERISTICA_GAS, INMUEBLE_CANT_AMBIENTES, INMUEBLE_ORIENTACION, INMUEBLE_DISPOSICION, INMUEBLE_SUPERFICIETOTAL, INMUEBLE_ANTIGUEDAD)
		SELECT DISTINCT m.INMUEBLE_TIPO_INMUEBLE, m.INMUEBLE_CARACTERISTICA_WIFI, m.INMUEBLE_CARACTERISTICA_CABLE, m.INMUEBLE_CARACTERISTICA_CALEFACCION, m.INMUEBLE_CARACTERISTICA_GAS, m.INMUEBLE_CANT_AMBIENTES, m.INMUEBLE_ORIENTACION, m.INMUEBLE_DISPOSICION, m.INMUEBLE_SUPERFICIETOTAL, m.INMUEBLE_ANTIGUEDAD
		FROM GD_ESQUEMA.MAESTRA m
		WHERE m.INMUEBLE_TIPO_INMUEBLE is not null
END 
GO

CREATE PROCEDURE SYSTEAM.CARGAR_INMUEBLE
AS
BEGIN
	INSERT INTO SYSTEAM.INMUEBLE
		(INMUEBLE_CODIGO, PROPIETARIO_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_DESCRIPCION, INMUEBLE_DIRECCION, INMUEBLE_EXPENSAS, INMUEBLE_BARRIO, LOCALIDAD_CODIGO, PROVINCIA_CODIGO, INMUEBLE_ESTADO_CODIGO, DETALLE_INMUEBLE_CODIGO)
		SELECT DISTINCT m.INMUEBLE_CODIGO, pr.PROPIETARIO_CODIGO, m.INMUEBLE_NOMBRE, m.INMUEBLE_DESCRIPCION, m.INMUEBLE_DIRECCION, m.INMUEBLE_EXPESAS, m.INMUEBLE_BARRIO, l.LOCALIDAD_CODIGO, p.PROVINCIA_CODIGO, ie.INMUEBLE_ESTADO_CODIGO, di.DETALLE_INMUEBLE_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN PROPIETARIO pr ON pr.PROPIETARIO_DNI = m.PROPIETARIO_DNI
		JOIN LOCALIDAD l on l.LOCALIDAD_NOMBRE = m.INMUEBLE_LOCALIDAD
		JOIN PROVINCIA p on p.PROVINCIA_NOMBRE = m.INMUEBLE_PROVINCIA
		JOIN INMUEBLE_ESTADO ie on ie.INMUEBLE_ESTADO = m.INMUEBLE_ESTADO
		JOIN DETALLE_INMUEBLE di ON di.INMUEBLE_TIPO_INMUEBLE = m.INMUEBLE_TIPO_INMUEBLE
		AND di.INMUEBLE_CARACTERISTICA_WIFI = m.INMUEBLE_CARACTERISTICA_WIFI
		AND di.INMUEBLE_CARACTERISTICA_CABLE = m.INMUEBLE_CARACTERISTICA_CABLE
		AND di.INMUEBLE_CARACTERISTICA_CALEFACCION = m.INMUEBLE_CARACTERISTICA_CALEFACCION
		AND di.INMUEBLE_CARACTERISTICA_GAS = m.INMUEBLE_CARACTERISTICA_GAS
		AND di.INMUEBLE_CANT_AMBIENTES = m.INMUEBLE_CANT_AMBIENTES
		AND di.INMUEBLE_ORIENTACION = m.INMUEBLE_ORIENTACION
		AND di.INMUEBLE_DISPOSICION = m.INMUEBLE_DISPOSICION
		AND di.INMUEBLE_SUPERFICIETOTAL = m.INMUEBLE_SUPERFICIETOTAL
		AND di.INMUEBLE_ANTIGUEDAD = m.INMUEBLE_ANTIGUEDAD
		WHERE m.INMUEBLE_CODIGO is not null 
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_ANUNCIO
AS 
BEGIN
	INSERT INTO SYSTEAM.ANUNCIO
		(ANUNCIO_CODIGO, ANUNCIO_FECHA_PUBLICACION, ANUNCIO_PRECIO_PUBLICADO, TIPO_ANUNCIO_CODIGO, ANUNCIO_COSTO_ANUNCIO, ANUNCIO_FECHA_FINALIZACION, MONEDA_CODIGO, ANUNCIO_ESTADO, ANUNCIO_TIPO_PERIODO, AGENTE_CODIGO, INMUEBLE_CODIGO)
		SELECT DISTINCT m.ANUNCIO_CODIGO, m.ANUNCIO_FECHA_PUBLICACION, m.ANUNCIO_PRECIO_PUBLICADO, ta.TIPO_ANUNCIO_CODIGO, m.ANUNCIO_COSTO_ANUNCIO, m.ANUNCIO_FECHA_FINALIZACION, mn.MONEDA_CODIGO, m.ANUNCIO_ESTADO, m.ANUNCIO_TIPO_PERIODO, ag.AGENTE_CODIGO, i.INMUEBLE_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN TIPO_ANUNCIO ta on m.ANUNCIO_TIPO_OPERACION = ta.TIPO_ANUNCIO_NOMBRE
		JOIN MONEDA mn on m.ANUNCIO_MONEDA = mn.MONEDA_NOMBRE
		JOIN AGENTE ag on ag.AGENTE_DNI = m.AGENTE_DNI
		JOIN INMUEBLE i on i.INMUEBLE_CODIGO = m.INMUEBLE_CODIGO
		WHERE m.ANUNCIO_CODIGO is not null
END 
GO

CREATE PROCEDURE SYSTEAM.CARGAR_MEDIO_PAGO
AS
BEGIN 
	WITH MediosDePago AS (
		SELECT PAGO_VENTA_MEDIO_PAGO AS MEDIO_PAGO_NOMBRE FROM GD_ESQUEMA.MAESTRA
		UNION
		SELECT PAGO_ALQUILER_MEDIO_PAGO AS MEDIO_PAGO_NOMBRE FROM GD_ESQUEMA.MAESTRA
	)
	INSERT INTO SYSTEAM.MEDIO_PAGO (MEDIO_PAGO_NOMBRE)
	SELECT DISTINCT MEDIO_PAGO_NOMBRE
	FROM MediosDePago
	WHERE MEDIO_PAGO_NOMBRE IS NOT NULL
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_VENTA
AS 
BEGIN
	INSERT INTO SYSTEAM.VENTA
		(VENTA_CODIGO, VENTA_FECHA, VENTA_PRECIO_VENTA, VENTA_COMISION, MONEDA_CODIGO, ANUNCIO_CODIGO)
		SELECT DISTINCT m.VENTA_CODIGO, m.VENTA_FECHA, m.VENTA_PRECIO_VENTA, m.VENTA_COMISION, mn.MONEDA_CODIGO, a.ANUNCIO_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN MONEDA mn on m.VENTA_MONEDA = mn.MONEDA_NOMBRE
		JOIN ANUNCIO a on a.ANUNCIO_CODIGO = m.ANUNCIO_CODIGO
		WHERE m.VENTA_CODIGO is not null 
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_PAGO_VENTA 
AS 
BEGIN
	INSERT INTO SYSTEAM.PAGO_VENTA
		(PAGO_VENTA_IMPORTE, MONEDA_CODIGO, PAGO_VENTA_COTIZACION, MEDIO_PAGO_CODIGO, VENTA_CODIGO)
		SELECT DISTINCT m.PAGO_VENTA_IMPORTE, mn.MONEDA_CODIGO, m.PAGO_VENTA_COTIZACION, mp.MEDIO_PAGO_CODIGO, v.VENTA_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN MONEDA mn on mn.MONEDA_NOMBRE = m.PAGO_VENTA_MONEDA
		JOIN MEDIO_PAGO mp on mp.MEDIO_PAGO_NOMBRE = m.PAGO_VENTA_MEDIO_PAGO
		JOIN VENTA v on v.VENTA_CODIGO = m.VENTA_CODIGO
		WHERE m.PAGO_VENTA_IMPORTE is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_ALQUILER
AS
BEGIN
	INSERT INTO SYSTEAM.ALQUILER
		(ALQUILER_CODIGO, ALQUILER_FECHA_INICIO, ALQUILER_FECHA_FIN, ALQUILER_CANT_PERIODOS, ALQUILER_DEPOSITO, ALQUILER_COMISION, ALQUILER_GASTOS_AVERIGUA, ALQUILER_ESTADO, INQUILINO_CODIGO, ANUNCIO_CODIGO)
		SELECT DISTINCT m.ALQUILER_CODIGO, m.ALQUILER_FECHA_INICIO, m.ALQUILER_FECHA_FIN, m.ALQUILER_CANT_PERIODOS, m.ALQUILER_DEPOSITO, m.ALQUILER_COMISION, m.ALQUILER_GASTOS_AVERIGUA, m.ALQUILER_ESTADO, iq.INQUILINO_CODIGO, a.ANUNCIO_CODIGO
		FROM gd_esquema.Maestra m
		JOIN INQUILINO iq on iq.INQUILINO_DNI = m.INQUILINO_DNI AND iq.INQUILINO_APELLIDO = m.INQUILINO_APELLIDO
		JOIN ANUNCIO a on a.ANUNCIO_CODIGO = m.ANUNCIO_CODIGO
		WHERE m.ALQUILER_CODIGO is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_PAGO_ALQUILER
AS
BEGIN
	INSERT INTO SYSTEAM.PAGO_ALQUILER
		(PAGO_ALQUILER_CODIGO, PAGO_ALQUILER_FECHA, PAGO_ALQUILER_FECHA_VENCIMIENTO, PAGO_ALQUILER_NRO_PERIODO, PAGO_ALQUILER_DESC, PAGO_ALQUILER_FECHA_INI, PAGO_ALQUILER_FECHA_FIN, PAGO_ALQUILER_IMPORTE, MEDIO_PAGO_CODIGO, ALQUILER_CODIGO)
		SELECT DISTINCT m.PAGO_ALQUILER_CODIGO, m.PAGO_ALQUILER_FECHA, m.PAGO_ALQUILER_FECHA_VENCIMIENTO, m.PAGO_ALQUILER_NRO_PERIODO, m.PAGO_ALQUILER_DESC, m.PAGO_ALQUILER_FEC_INI, m.PAGO_ALQUILER_FEC_FIN, m.PAGO_ALQUILER_IMPORTE, mp.MEDIO_PAGO_CODIGO, al.ALQUILER_CODIGO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN MEDIO_PAGO mp on mp.MEDIO_PAGO_NOMBRE = m.PAGO_ALQUILER_MEDIO_PAGO
		JOIN ALQUILER al on al.ALQUILER_CODIGO = m.ALQUILER_CODIGO
		WHERE m.PAGO_ALQUILER_CODIGO is not null
END
GO

CREATE PROCEDURE SYSTEAM.CARGAR_DETALLE_ALQUILER
AS
BEGIN
	INSERT INTO SYSTEAM.DETALLE_ALQUILER
		(ALQUILER_CODIGO, DETALLE_ALQ_NRO_PERIODO_INI, DETALLE_ALQ_NRO_PERIODO_FIN, DETALLE_ALQUILER_PRECIO)
		SELECT DISTINCT al.ALQUILER_CODIGO, m.DETALLE_ALQ_NRO_PERIODO_INI, m.DETALLE_ALQ_NRO_PERIODO_FIN, m.DETALLE_ALQ_PRECIO
		FROM GD_ESQUEMA.MAESTRA m
		JOIN ALQUILER al on al.ALQUILER_CODIGO = m.ALQUILER_CODIGO
		WHERE m.DETALLE_ALQ_NRO_PERIODO_INI is not null
END 
GO


EXEC SYSTEAM.CARGAR_MONEDA
EXEC SYSTEAM.CARGAR_TIPO_ANUNCIO
EXEC SYSTEAM.CARGAR_LOCALIDAD
EXEC SYSTEAM.CARGAR_PROVINCIA
EXEC SYSTEAM.CARGAR_SUCURSAL
EXEC SYSTEAM.CARGAR_AGENTE
EXEC SYSTEAM.CARGAR_PROPIETARIO
EXEC SYSTEAM.CARGAR_COMPRADOR
EXEC SYSTEAM.CARGAR_INQUILINO
EXEC SYSTEAM.CARGAR_INMUEBLE_ESTADO
EXEC SYSTEAM.CARGAR_DETALLE_INMUEBLE
EXEC SYSTEAM.CARGAR_INMUEBLE
EXEC SYSTEAM.CARGAR_ANUNCIO
EXEC SYSTEAM.CARGAR_MEDIO_PAGO
EXEC SYSTEAM.CARGAR_VENTA
EXEC SYSTEAM.CARGAR_PAGO_VENTA
EXEC SYSTEAM.CARGAR_ALQUILER
EXEC SYSTEAM.CARGAR_PAGO_ALQUILER
EXEC SYSTEAM.CARGAR_DETALLE_ALQUILER